"""auth: user, auth_identity, refresh_token, plant.user_id

Revision ID: 0002_auth
Revises: 0001_baseline
Create Date: 2026-07-14 20:36:01.562839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0002_auth'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)

    op.create_table('authidentity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sa.Enum('apple', 'google', name='authprovider'), nullable=False),
    sa.Column('provider_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_at_signup', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('apple_refresh_token_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_sub')
    )
    with op.batch_alter_table('authidentity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authidentity_user_id'), ['user_id'], unique=False)

    op.create_table('refreshtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('family_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refreshtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refreshtoken_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refreshtoken_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_plant_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_plant_user_id', 'user', ['user_id'], ['id'])

    # Backfill: create the dev@local placeholder user and assign every
    # pre-auth plant to it, so existing/seeded data survives the cutover.
    # (user_id stays schema-nullable — SQLite can't add NOT NULL to existing
    # rows; ownership is enforced at the application layer from Phase 6.)
    from datetime import datetime
    from uuid import uuid4

    conn = op.get_bind()
    orphans = conn.execute(
        sa.text("SELECT COUNT(*) FROM plant WHERE user_id IS NULL")
    ).scalar()
    if orphans:
        dev_id = str(uuid4())
        conn.execute(
            sa.text(
                "INSERT INTO user (id, email, display_name, created_at) "
                "VALUES (:id, 'dev@local', 'Dev User', :now)"
            ),
            {"id": dev_id, "now": datetime.utcnow().isoformat(sep=" ")},
        )
        conn.execute(
            sa.text("UPDATE plant SET user_id = :uid WHERE user_id IS NULL"),
            {"uid": dev_id},
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plant_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_plant_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('refreshtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refreshtoken_user_id'))
        batch_op.drop_index(batch_op.f('ix_refreshtoken_family_id'))

    op.drop_table('refreshtoken')
    with op.batch_alter_table('authidentity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authidentity_user_id'))

    op.drop_table('authidentity')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
