#!/usr/bin/env bash
#
# PlantAdvocate — one-command iOS Simulator build + launch.
#
#   cd mobile && npm run sim
#
# What it does, in order:
#   1. Syncs your checkout EXACTLY to origin/<branch> (discards local build
#      noise like the package.json edit prebuild leaves behind — this is a
#      build machine, code is authored elsewhere and pushed).
#   2. Stamps the build with its git commit + an incrementing build number
#      (shown in the app under Settings → About, so you always know what's
#      running).
#   3. Rebuilds native code ONLY when native deps / app.json changed. JS-only
#      edits don't need a rebuild — they hot-reload through Metro. So most runs
#      skip the slow prebuild.
#   4. Typechecks (fails fast before a multi-minute build).
#   5. Makes sure Metro is running, then builds (signed, so the keychain works),
#      installs, and launches on the simulator.
#
# Flags:  --full   force a clean prebuild even if nothing native changed
#         --no-sync skip the git sync (build exactly what's on disk)
set -uo pipefail

BRANCH="claude/plant-advocate-screenshots-xxt8ed"
SIM="iPhone 17 Pro"
BUNDLE_ID="com.allisonbowman.plantadvocate"
SCHEME="PlantAdvocate"
WORKSPACE="ios/PlantAdvocate.xcworkspace"
DERIVED="/tmp/pa-build"
BUILD_LOG="/tmp/pa-build.log"
METRO_LOG="/tmp/pa-metro.log"

FORCE_PREBUILD=0
DO_SYNC=1
for arg in "$@"; do
  case "$arg" in
    --full) FORCE_PREBUILD=1 ;;
    --no-sync) DO_SYNC=0 ;;
  esac
done

# cd to mobile/ (this script lives in mobile/scripts/)
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(git rev-parse --show-toplevel)"

g="\033[1;32m"; r="\033[1;31m"; y="\033[1;33m"; z="\033[0m"
step() { printf "${g}▶ %s${z}\n" "$1"; }
note() { printf "${y}• %s${z}\n" "$1"; }
die()  { printf "${r}✖ %s${z}\n" "$1"; exit 1; }

# ── 1. Sync exactly to the remote branch ──────────────────────────────────────
if [[ "$DO_SYNC" == "1" ]]; then
  step "Syncing $BRANCH from origin…"
  git -C "$ROOT" fetch -q origin "$BRANCH" || die "git fetch failed — check your connection."
  git -C "$ROOT" checkout -q -f "$BRANCH" 2>/dev/null \
    || git -C "$ROOT" checkout -q -b "$BRANCH" "origin/$BRANCH" \
    || die "could not switch to $BRANCH."
  git -C "$ROOT" reset --hard -q "origin/$BRANCH" || die "git reset failed."
fi
COMMIT="$(git -C "$ROOT" rev-parse --short HEAD)"
note "commit $COMMIT"

# ── 2. Version stamp ──────────────────────────────────────────────────────────
NUM_FILE=".sim-build-number"
NUM=$(( $(cat "$NUM_FILE" 2>/dev/null || echo 0) + 1 ))
echo "$NUM" > "$NUM_FILE"
STAMP="$(date '+%Y-%m-%d %H:%M')"
cat > src/buildInfo.ts <<EOF
// Auto-generated by scripts/sim-build.sh — do not edit. Committed defaults are
// used for EAS/production builds where this script doesn't run.
export const BUILD_COMMIT = '$COMMIT';
export const BUILD_NUMBER = $NUM;
export const BUILT_AT = '$STAMP';
EOF
note "build #$NUM · $COMMIT · $STAMP"

# ── 3. Native rebuild only when native deps / app config changed ──────────────
HASH_FILE=".sim-native-hash"
NATIVE_HASH="$(cat package.json app.json | shasum | awk '{print $1}')"
if [[ "$FORCE_PREBUILD" == "1" || ! -d ios || "$(cat "$HASH_FILE" 2>/dev/null)" != "$NATIVE_HASH" ]]; then
  step "Native deps/config changed — npm install + prebuild (slow, a few min)…"
  npm install || die "npm install failed."
  npx expo prebuild -p ios --clean || die "expo prebuild failed."
  echo "$NATIVE_HASH" > "$HASH_FILE"
else
  note "no native changes — skipping prebuild (JS hot-reloads via Metro)."
fi

# ── 4. Typecheck pre-flight ───────────────────────────────────────────────────
step "Typechecking…"
npx tsc --noEmit || die "tsc failed — fix the type errors above before building."

# ── 5. Ensure Metro is up ─────────────────────────────────────────────────────
if ! lsof -ti tcp:8081 >/dev/null 2>&1; then
  step "Starting Metro in the background (log: $METRO_LOG)…"
  nohup npx expo start >"$METRO_LOG" 2>&1 &
  for _ in $(seq 1 25); do lsof -ti tcp:8081 >/dev/null 2>&1 && break; sleep 1; done
  lsof -ti tcp:8081 >/dev/null 2>&1 || note "Metro didn't come up — check $METRO_LOG (build continues)."
else
  note "Metro already running on :8081."
fi

# ── 6. Build → install → launch ───────────────────────────────────────────────
step "Building for $SIM (silent for a few minutes — normal)…"
xcodebuild \
  -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug \
  -sdk iphonesimulator -destination "platform=iOS Simulator,name=$SIM" \
  -derivedDataPath "$DERIVED" >"$BUILD_LOG" 2>&1 \
  || { tail -40 "$BUILD_LOG"; die "xcodebuild failed (full log: $BUILD_LOG)."; }

APP="$(find "$DERIVED/Build/Products/Debug-iphonesimulator" -maxdepth 1 -name '*.app' | head -1)"
[[ -n "$APP" ]] || die "build reported success but no .app was produced."

step "Installing + launching…"
open -a Simulator
xcrun simctl boot "$SIM" 2>/dev/null || true
xcrun simctl uninstall booted "$BUNDLE_ID" 2>/dev/null || true
xcrun simctl install booted "$APP" || die "simctl install failed."
xcrun simctl launch booted "$BUNDLE_ID" >/dev/null || die "simctl launch failed."

printf "${g}✅ LAUNCHED — PlantAdvocate build #%s (%s) on %s${z}\n" "$NUM" "$COMMIT" "$SIM"
printf "   JS edits hot-reload via Metro. Re-run 'npm run sim' when native deps change.\n"
