"""baseline: schema as of catalog expansion

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-07-14 20:33:11.339741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('home', 'nursery', 'community_garden', 'conservation', 'research', name='environmenttype'), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scientific_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('light_need', sa.Enum('low', 'medium', 'bright_indirect', 'direct', name='lightneed'), nullable=False),
    sa.Column('humidity_pct_min', sa.Integer(), nullable=False),
    sa.Column('humidity_pct_max', sa.Integer(), nullable=False),
    sa.Column('temp_f_min', sa.Integer(), nullable=False),
    sa.Column('temp_f_max', sa.Integer(), nullable=False),
    sa.Column('soil_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('toxic_to_pets', sa.Boolean(), nullable=False),
    sa.Column('care_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sa.Enum('curated', 'perenual', 'llm_generated', name='speciessource'), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('review_status', sa.Enum('approved', 'needs_review', 'verified', name='reviewstatus'), nullable=False),
    sa.Column('review_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_species_common_name'), ['common_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_species_scientific_name'), ['scientific_name'], unique=False)

    op.create_table('careschedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('care_type', sa.Enum('water', 'fertilize', 'mist', 'prune', 'repot', 'rotate', 'clean', 'other', name='caretype'), nullable=False),
    sa.Column('interval_days_min', sa.Integer(), nullable=False),
    sa.Column('interval_days_max', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('species_id', 'care_type')
    )
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('maturity_stage', sa.Enum('seedling', 'juvenile', 'mature', 'flowering', name='maturitystage'), nullable=False),
    sa.Column('acquired_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('soil_moisture_at_acquisition', sa.Enum('dry', 'moist', 'wet', name='soilmoisture'), nullable=True),
    sa.Column('leaf_condition_at_acquisition', sa.Enum('healthy', 'yellowing', 'browning', 'wilting', 'pest_damage', 'dropping', name='leafcondition'), nullable=True),
    sa.Column('pest_observed_at_acquisition', sa.Boolean(), nullable=False),
    sa.Column('intake_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_uuid')
    )
    op.create_table('speciestrait',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('trait', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('species_id', 'trait')
    )
    with op.batch_alter_table('speciestrait', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speciestrait_trait'), ['trait'], unique=False)

    op.create_table('carelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('water', 'fertilize', 'mist', 'prune', 'repot', 'rotate', 'clean', 'other', name='caretype'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stewardshiprecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('installation_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('transfer_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stewardshiprecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stewardshiprecord_installation_uuid'), ['installation_uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stewardshiprecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stewardshiprecord_installation_uuid'))

    op.drop_table('stewardshiprecord')
    op.drop_table('carelog')
    with op.batch_alter_table('speciestrait', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speciestrait_trait'))

    op.drop_table('speciestrait')
    op.drop_table('plant')
    op.drop_table('careschedule')
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_species_scientific_name'))
        batch_op.drop_index(batch_op.f('ix_species_common_name'))

    op.drop_table('species')
    op.drop_table('environment')
    # ### end Alembic commands ###
